### ISSUE TITLE
Convert commad crash.

### ISSUE THREAD

**Issue by reelleer** [jessehouwing/Blogger2Ghost#11]
Hi,

Mapping command generate author object with `"from_google_plus_url" : nulll` because AtomReader.ReadPerson return _Uri_ property in null.

If I run convert command It crash with this error:

```
Executing convert (Convert blogger export to ghost import):
    In : C:\..\Blog\blog-10-17-2018.xml
    IncludeDrafts : False
    Markdown : True
    Out : C:\...\Blog\migration\
    Overwrite : True
    RedirectPermanent : True
    Template : null
    Zip : True

Reading : C:\...\Blog\migration\urls.json
Reading : C:\...\Blog\migration\images.json
Reading : C:\...\Blog\migration\authors.json
Reading : C:\...\Blog\migration\tags.json
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Blogger2Ghost.Commands.ConvertCommand.ConvertUser(IList`1 users, UserMapping[] mappings, ISyndicationPerson user)
   at Blogger2Ghost.Commands.ConvertCommand.ConvertUsers(IList`1 users)
   at Blogger2Ghost.Commands.ConvertCommand.Run(String[] remainingArguments)
```
The XML file author elment:

```
<author>
  <name>Rolando Espinosa</name>
  <uri>https://plus.google.com/111990753997876527141</uri>
  <email>noreply@blogger.com</email>
  <gd:image rel='http://schemas.google.com/g/2005#thumbnail' width='32' height='32' src='//lh3.googleusercontent.com/-3NfhBfOJ314/AAAAAAAAAAI/AAAAAAAABDA/snTOhxCmhiM/s32-c/photo.jpg'/>
</author>
```

**Comment by jessehouwing** [comment]
Google+ has been deprecated. I suspect that caused a format change on Blogger's side. Since I've moved and won't be importing any more blogs, I can't really fix this. If you provide a pull request or can provide me with an export file and mappings, I may be able to help you fix this.
